apiVersion: v1
kind: Service
metadata:
  name: djangoblog-svc
  labels:
    app: djangoblog
spec:
  type: ClusterIP
  selector:
    app: djangoblog
  ports:
    - name: http
      port: 80
      targetPort: 3000

